//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDepartman
    {
        public int DepartmanId { get; set; }
        public string DepartmanAdi { get; set; }
    }
}
