//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIzinTalep
    {
        public int IzinTalepId { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<System.DateTime> TalepTarihi { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<int> OnaylanKisiId { get; set; }
    }
}
