//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullanici
    {
        public int KullaniciId { get; set; }
        public Nullable<int> KisiId { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> SonGirisZamani { get; set; }
    }
}
