//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKisi
    {
        public int KisiId { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public int BolumId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<long> TCKimlik { get; set; }
        public string DogumYeriIl { get; set; }
        public string DogumYeriIlce { get; set; }
        public string AnneAdi { get; set; }
        public string BabaAdi { get; set; }
    }
}
