//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKisiEgitim
    {
        public int KisiEgitimId { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<int> EgitimDurumId { get; set; }
        public Nullable<int> BaslangicYili { get; set; }
        public Nullable<int> BitisYili { get; set; }
        public Nullable<int> OkulId { get; set; }
        public Nullable<int> BitirmeNotu { get; set; }
    }
}
